In [2]:
import pandas as pd

dataf_svm = pd.read_csv("E:\\Monali\\Class\\machineLearning\\SVM\\svm_dataset.csv")

dataf_svm.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [3]:
P = dataf_svm.drop('price', axis=1)

q = dataf_svm['price']


print('Shape of P = ', P.shape)

print('Shape of q = ', q.shape)

Shape of P =  (7120, 107)
Shape of q =  (7120,)


In [5]:
from sklearn.model_selection import train_test_split

P_train, P_test, q_train, q_test = train_test_split(P, q, test_size=0.2, random_state=51)


print('Shape of P_train = ', P_train.shape)

print('Shape of q_train = ', q_train.shape)

print('Shape of P_test = ', P_test.shape)

print('Shape of q_test = ', q_test.shape)


Shape of P_train =  (5696, 107)
Shape of q_train =  (5696,)
Shape of P_test =  (1424, 107)
Shape of q_test =  (1424,)


In [6]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(P_train)

P_train = sc.transform(P_train)

P_test = sc.transform(P_test)


In [7]:
from sklearn.svm import SVR

svr_rbf = SVR(kernel='rbf')

svr_rbf.fit(P_train, q_train)

svr_rbf.score(P_test, q_test)

0.2063803584082815

In [8]:
svr_linear = SVR(kernel='linear')

svr_linear.fit(P_train, q_train)

svr_linear.score(P_test, q_test)

0.7962725308517551

In [9]:
svr_poly = SVR(kernel='poly',degree=2,)

svr_poly.fit(P_train, q_train)

svr_poly.score(P_test, q_test)

0.18266215211874626

In [10]:
P_test[0]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [11]:
svr_linear.predict([P_test[0]])

array([86.53673464])

In [12]:
q_pred = svr_linear.predict(P_test)

q_pred

array([ 86.53673464,  33.70390806, 122.48356838, ...,  26.23978753,
        64.52634655, 176.17532793])

In [13]:
for i in svr_linear.predict(P_test):
    print(i)

86.53673464480366
33.70390805746797
122.48356837855707
81.29571341865476
40.78096429465638
35.463989810914455
53.9260605535052
79.846422245661
101.55884291020038
63.654308962317984
104.95905131109811
241.7077787453509
219.8409257968223
223.65223621502733
159.0443214109216
49.34163752148976
90.21093672286531
90.96685873151692
153.6189383051105
54.029579911930846
70.59238853276031
49.01574841952881
56.548997020914626
71.13525441332261
213.75438126132212
297.8821568228441
10.947803017124173
101.97507942667335
152.3387837045973
166.70273497270557
56.23321257898403
61.447665897462215
186.303376002893
255.72745493198286
108.54976039570468
47.84571779604632
61.180378162447695
104.8010638971968
25.07449803663654
91.03861872709086
70.16445565341382
39.775186799850054
83.36592180280346
80.0175654346784
79.35504814683665
55.72792557700473
82.88934182746428
98.86398654987525
87.66781798433934
45.86736614657664
50.8617383071177
17.9537045670952
66.8817957645961
82.80646013629107
173.4930771362035
3

In [14]:
q_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [15]:
from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(q_test, q_pred)

rmse = np.sqrt(mse)

print('MSE = ', mse)

print('RMSE = ', rmse)

MSE =  4093.4831852475745
RMSE =  63.9803343633618
